# Generated by Django 6.0.5 on 2026-06-08 21:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0010_rename_frame_type_card_frametype'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CardsOnDeck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_quantity', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(3)])),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_on_deck', to='cards.card')),
            ],
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('cards', models.ManyToManyField(related_name='deck_cards', through='decks.CardsOnDeck', to='cards.card')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cardsondeck',
            name='deck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deck_containing_card', to='decks.deck'),
        ),
        migrations.AlterUniqueTogether(
            name='cardsondeck',
            unique_together={('deck', 'card')},
        ),
    ]
