# Generated by Django 6.0.5 on 2026-05-13 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='hp',
        ),
    ]
