# Generated by Django 6.0.5 on 2026-05-13 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_remove_card_hp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='atk',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='defense',
            field=models.IntegerField(null=True),
        ),
    ]
