# Generated by Django 6.0.5 on 2026-05-13 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_alter_card_atk_alter_card_defense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='level',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
