# Generated by Django 6.0.5 on 2026-05-14 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_alter_card_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='attribute',
            field=models.CharField(default='unknown', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='frametype',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='level',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='race',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='card',
            name='type',
            field=models.CharField(max_length=50),
        ),
    ]
