# Generated by Django 6.0.5 on 2026-05-14 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_card_attribute_card_frametype_alter_card_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='id',
            field=models.CharField(primary_key=True, serialize=False),
        ),
    ]
