# Generated by Django 6.0.5 on 2026-05-14 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_alter_card_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
