# Generated by Django 6.0.5 on 2026-05-14 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0007_alter_card_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='frametype',
            new_name='frameType',
        ),
    ]
