# Generated by Django 6.0.5 on 2026-05-15 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0008_rename_frametype_card_frametype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='frameType',
            new_name='frame_type',
        ),
    ]
