# Generated by Django 6.0.5 on 2026-05-15 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0009_rename_frametype_card_frame_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='frame_type',
            new_name='frameType',
        ),
    ]
